### ISSUE TITLE
Any plans to rename cli?

### ISSUE THREAD

**Issue by js-kyle** [ghiscoding/lerna-lite#28]
Hi there

I was wondering if it would be considered to update the cli to `learna-lite` in a future version, as opposed to the two `ws-*` commands? The reasoning behind this would be for ease of development, where developers familiar with lerna could easily recognise the use of this project as lerna like commands, whereas `ws-*`  is not familiar

### Motivation / Use Case
Ease of migration and familiarity for developers

### Expected Behavior
`ws-roller version` - > `lerna-lite version` etc

**Comment by ghiscoding** [comment]
not really, there are 2 CLIs because `run` is totally optional (as pointed out in the readme) and the naming came from the original repo name I had when I created. Migration is easy enough, do a find a replace `lerna run` => `ws-runner run` and `lerna version` to `ws-roller version` (same for `publish`). That is simple enough, and I don't want to have only 1 CLI because I want to keep `run` as optional package (you won't download it if you don't need it and for you need different CLIs) as oppose to Lerna which is 1 CLI yes **but** it also requires the users to download the entire library (like or not) and in my monorepo I have never use anything else but 3 commands that I have in Lerna-Lite... so that's the reason that it's 2 CLIs, and I think it's better to keep names that aren't too close to `lerna <command>` so that users know that it's not an all in 1 like Lerna was.

**Comment by js-kyle** [comment]
> I think it's better to keep names that aren't too close to lerna <command> so that users understand that it's not an all in 1 like Lerna was.

`lerna-lite` definitely implyies at a glance that it is not the full feature set of lerna

The benefit is that at a glance, any developer on a project can recognise that it is operating similar to lerna. If they have questions they will be able to search for `lerna-lite` documentation or look at the `lerna-lite` module. At present `ws-*` has no correlation to the module name so is pretty confusing in itself. For example searching `ws-roller` in npm returns no results

But that is just my feedback - take it as you please :)

**Comment by ghiscoding** [comment]
I don't see how that could be achievable with 2 separate CLIs, the best I could do is rename `ws-roller` to `lerna-lite` but then we would still have `ws-runner` for `run` and that is even more confusion, so unless I merge all commands into 1 CLI (which I don't want to do) then I don't see this as something doable unless you have better ideas

**Comment by ghiscoding** [comment]
I don't see how changing `ws` to `ll` would help in anything, unless you're trying to say to keep only 1 CLI as `ll` (which I'll say again I want to keep 2 CLIs). I seriously don't see how hard it can be to in your CI job and do a search & replace, 5min max. You cannot execute `run`, `publish` and `version` at the same time, so I don't see how keeping 2 CLIs is hurting anything. 

Keeping only 1 CLI (like Lerna) would mean that `run` would no longer be optional and I don't want to do that, I have high hope that it will become useless in the future when NPM Workspaces add this functionality and I'm sure certain users of this lib are only interested in the publish/version features and do not wish to download extra bits for `run` that they wouldn't use. Keeping 1 CLI means nothing is optional (like Lerna, you get all of it, regardless if you use it or not which is what I wanted to avoid)

**Comment by js-kyle** [comment]
> I seriously don't see how hard it can be to in your CI job and do a search & replace, 5min max
This is not about migration - it is the fact that ws-* commands are unrecognisable to developers in a project

**Comment by mrchief** [comment]
`ws` has no relation that you can derive intuitively to lerna-lite. `ll` is just lerna-lite abbreviated. 

Alternatively, have you looked at making a command runner as part of core that understands `version|publish|run` as commands and routes them to individual clis as needed?

So e.g., `lerna-lite run` would look for `@lerna-lite/run` installed in the node_modules (local or global) and would invoke it if found, otherwise print a warning asking users to install the package

**Comment by ghiscoding** [comment]
> Alternatively, have you looked at making a command runner as part of core that understands `version|publish|run` as commands and routes them to individual clis as needed?
> 
> So e.g., `lerna-lite run` would look for `@lerna-lite/run` installed in the node_modules (local or global) and would invoke it if found, otherwise print a warning asking users to install the package

If you know how to do that and keep the `run` command optional, I'd be happy to get PR on this, I personally never created CLI code before creating this project and there are some part of the original Lerna CLI that I don't understand how it works.

I'm currently mostly focused on adding all Lerna's unit tests as much as possible so that we can add features after without too much stress

**Comment by mrchief** [comment]
I'm looking at replacing lerna and I've been following the "lerna is largely unmaintained topic" so I'm aware of the work in general. I currently use a combo of release-please and lerna to manage prereleases, beta packages and releases and I would like to avoid having 2 ringmasters. You're doing great work and we appreciate all the effort. Your philosophy is sound but we also need to manage developer expectations and overall experience. I'd try to see if I can send a PR but work's been hectic lately and it may not pan out as quickly, so no promises! :)

**Comment by mrchief** [comment]
Spitballing here but something along these lines

```
// packages/cli.ts

async function runHandler(argv: any) {
  logCliVersion();

  try {
    const { handler: RunCli } = await import('@lerna-lite/run');
    RunCli(argv);
  } catch (e) {
    console.error(
      '@lerna-lite/run not found. Please install it with `npm install @lerna-lite/run`'
    );
  }
}

yargs
   ...
   .command({
    command: 'run <script>',
    describe: 'Run an npm script in each package that contains that script',
    handler: runHandler,
  })

// packages/run/cli
function handler () ...
yargs...
...
export { handler }
```

**Comment by ghiscoding** [comment]
After few days working on this, the feature is in, so hopefully this will clear the last hurdle for people who want to migrate from Lerna to Lerna-Lite. I basically copied over the original Lerna CLI and even used the exact same name so it's a full drop-in replacement, just swap Lerna to Lerna-Lite in your dependencies and you'll be good to go. See the new [release](https://github.com/ghiscoding/lerna-lite/releases) and I decided to make it a `major` as `1.0.0`

I also implemented what @mrchief suggested so that I could keep `run` as an optional package and I just tried it in my own repo to not install it and as expected I get the error that was suggested.

So hopefully everyone can enjoy it and I can close the subject and move on to something else 😉 

![image](https://user-images.githubusercontent.com/643976/158302463-8d37c4d5-b546-42b1-9d2d-c682e0203d3b.png)
