### ISSUE TITLE
ws-roller version does not prompt for next version

### ISSUE THREAD

**Issue by webholics** [ghiscoding/lerna-lite#44]
### Your Environment

| Software             | Version(s) |
| -------------------- | ---------- |
| Lerna-Lite           | 0.36        |
| NodeJS               | 16.13.1        |
| TypeScript           | -        |

### Describe the Bug
`npx ws-roller version` does not prompt which version you want to create (major, minor, etc.) as stated in the docs:

`ws-roller version       # select from prompt(s)`

### Steps to Reproduce
`npx ws-roller version`

### Expected Behavior
Prompt whether you want to create a new major, minor, patch, etc. version.

### Current Behavior
Always just creates a new patch version.

### Possible Solution
See how current version of lerna does it. I migrated from lerna and the behaviour is different.

### Code Sample
`npx ws-roller version`

**Comment by webholics** [comment]
Its in this file: https://github.com/lerna/lerna/blob/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/commands/version/lib/prompt-version.js

**Comment by ghiscoding** [comment]
so is that without `conventional-commit` enabled? I have never seen this prompt but I think it's because I always use the conventional commit flag. I pushed a new version which has some code change copied from to the original code, it's not necessarily to fix this issue but it was code I put when adding more of the original Lerna's unit tests, anyway you could give it a try, if that doesn't help then it would probably require the newer CLI change and I'm not sure when I will do that

**Comment by webholics** [comment]
Yes its without `conventional-commits` enabled. We are managing the versions manually.

**Comment by ghiscoding** [comment]
I had some code to enable `conventional-commits` by default, which was different compare to original Lerna, however I rolled back that code in latest version. So it was probably the issue and it might have worked for you with previous version if you had manually disabled it... anyway it's now the same as Lerna

**Comment by ghiscoding** [comment]
I did a dry-run and it does prompt for a version with latest release `0.3.7`, so I'll assume this is fixed and I can close the issue
